### ISSUE TITLE
windows doesn't unload nvram

### ISSUE THREAD

**Issue by earonesty** [abetlen/llama-cpp-python#723]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

you should be able to load a model.  then unload (del) it then load another.   on linux this works.   on windows it doesn't.   the gpu will eventually run out of ram

on windows, i can load/run a single model (i like to use the llama server), it works fine.   when swapping models, it runs out of nvram.

# Current Behavior

same program running on linux (swapping between models), doesn't have this error
```
CUDA error 2 at C:\Users\erik\AppData\Local\Temp\tmp6un1fgb6\llama_cpp_python-0.2.2\vendor\llama.cpp\ggml-cuda.cu:6439: out of memory
```

# Environment and Context

Linux (works fine)
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
Linux 129-213-145-111 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. step 1, build llama with cuda support
2. step 2, load any model that uses most of nvram
3. step 3, delete that model, triggering the `__del__` handler and load another

i also tried manually calling llama_free_model on llama.model and llama_free_ctx on llama.ctx, to no avail

i suspect this is a problem with the upstream code base (llama.cpp), but i think you should know about it

**Comment by abetlen** [comment]
Yeah if you create a minimal test with the low-level api and it's still not freeing it's likely an upstream bug. Just out of curiosity can you try also calling llama_backend_free() after?

**Comment by earonesty** [comment]
ok, i tested it in c++, and it seems to work.   (took simple.cpp, called load/free in a loop, and it works fine)

**Comment by earonesty** [comment]
if i do the same thing in python it fails:

```
    llama_cpp.llama_backend_init(params.get('numa', None))

    ctx_params = llama_cpp.llama_context_default_params()

    model = llama_cpp.llama_load_model_from_file(params['model'].encode(), ctx_params)
    llama_cpp.llama_free_model(model)

    model = llama_cpp.llama_load_model_from_file(params['model'].encode(), ctx_params)
    llama_cpp.llama_free_model(model)

    model = llama_cpp.llama_load_model_from_file(params['model'].encode(), ctx_params)
    llama_cpp.llama_free_model(model)
```

but only on windows....

**Comment by earonesty** [comment]
i never tried calling backend_free because that's supposedly reserved for "process complete"

**Comment by earonesty** [comment]
ok, confirmed i cannot repro with the low level api.   trying with higher level now.

**Comment by earonesty** [comment]
ha!  i found the problem.   i was trying to reload a model using the llama-cpp-python server.   and there a global llama object.   so what was happening is it was that __del__ wasn't getting called reliably *before* the new model was loaded.   

explicitly calling `del llama_cpp.server.app.llama` fixed this
